services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/app
    command: tail -f /dev/null
    ports:
      - "8000:8000"
