services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/app
    command: tail -f /dev/null
    ports:
      - "8000:8000"

  rabbitmq:
    image: "rabbitmq:4.1.3-management"
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
